apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground-deployment
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - image: docker.io/wil42/playground:v1
        name: wil-playground
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: wil-playground
